agencia/agencia/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('box_office/', include('apps.boleteria.urls')),
    path('garage/', include('apps.flota.urls')),
]

agencia/apps/boleteria/urls.py
from django.urls import path
from apps.boleteria import views as view_boleteria
from apps.boleteria.api import apis as apis_boleteria

app_name='box_office'

urlpatterns = [
    path('api/passenger/list', apis_boleteria.passenger_api_view, name='api-passenger-list'),
    path('api/passenger/detail/<int:pk>/', apis_boleteria.passenger_detail_view, name='api-passenger-detail'),

    path('api/ticket/list', apis_boleteria.ticket_api_view, name='api-ticket-list'),
    path('api/ticket/detail/<int:pk>/', apis_boleteria.ticket_detail_view, name='api-ticket-detail'),
    
    path('api/ticket/list/buy', apis_boleteria.list_tickets_for_buy, name='api-ticket-list-buy'),
    path('api/ticket/list/sold', apis_boleteria.list_sold_tickets, name='api-ticket-list-sold'),
    path('api/ticket/pay', apis_boleteria.pay_ticket, name='api-ticket-pay'),

    path('ticket/buy', view_boleteria.ticket_buy, name='ticket-buy'),
    path('ticket/statistics', view_boleteria.statistics, name='statistics'),
    path('ticket/statistics/average', apis_boleteria.average_of_passengers, name='statistics-average'),
    path('ticket/statistics/percentage', apis_boleteria.percentage_buses_route, name='statistics-percentage'),
]

agencia/apps/flota/urls.py
from django.urls import path
from apps.flota import views as view_flota
from apps.flota.api import apis as apis_flota

app_name='garage'

urlpatterns = [
    # APIs
    path('api/chauffeur/list', apis_flota.chauffeur_api_view, name='api-chauffeur-list'),
    path('api/chauffeur/detail/<int:pk>/', apis_flota.chauffeur_detail_view, name='api-chauffeur-detail'),
    path('api/chauffeur/assing_route/<int:pk>/', apis_flota.chauffeur_assing_route, name='api-chauffeur-assing-route'),
    path('api/chauffeur/get_assinged_routes/<int:pk>/', apis_flota.chauffeur_get_assinged_routes, name='api-chauffeur-get-assinged-route'),
    path('api/chauffeur/unassing_route/<int:pk>/', apis_flota.chauffeur_unassing_route, name='api-chauffeur-unassing-route'),
    path('api/chauffeur/add/route/', apis_flota.chauffeur_add_route, name='api-chauffeur-add-route'),
    path('api/chauffeur/remove/route/', apis_flota.chauffeur_remove_route, name='api-chauffeur-remove-route'),

    path('api/bus/list', apis_flota.bus_api_view, name='api-bus-list'),
    path('api/bus/detail/<int:pk>/', apis_flota.bus_detail_view, name='api-bus-detail'),

    path('api/route/list', apis_flota.route_api_view, name='api-route-list'),
    path('api/route/detail/<int:pk>/', apis_flota.route_detail_view, name='api-route-detail'),
    path('api/route/assing_bus/<int:pk>/', apis_flota.route_assing_bus, name='api-route-assing-bus'),
    path('api/route/get_assinged_buses/<int:pk>/', apis_flota.route_get_assinged_buses, name='api-route-get-assinged-buses'),
    path('api/route/unassing_bus/<int:pk>/', apis_flota.route_unassing_bus, name='api-route-unassing-bus'),
    path('api/route/add/bus/', apis_flota.route_add_bus, name='api-route-add-bus'),
    path('api/route/remove/bus/', apis_flota.route_remove_bus, name='api-route-remove-bus'),

    path('api/schedule/list', apis_flota.schedule_api_view, name='api-schedule-list'),
    path('api/schedule/detail/<int:pk>/', apis_flota.schedule_detail_view, name='api-schedule-detail'),
    path('api/schedule/assing_route/<int:pk>/', apis_flota.schedule_assing_route, name='api-schedule-assing-route'),
    path('api/schedule/get_assinged_routes/<int:pk>/', apis_flota.schedule_get_assinged_routes, name='api-schedule-get-assinged-route'),
    path('api/schedule/unassing_route/<int:pk>/', apis_flota.schedule_unassing_route, name='api-schedule-unassing-route'),
    path('api/schedule/add/route/', apis_flota.schedule_add_route, name='api-schedule-add-route'),
    path('api/schedule/remove/route/', apis_flota.schedule_remove_route, name='api-schedule-remove-route'),

    path('api/bus_route/list', apis_flota.bus_route_api_view, name='api-bus_route-list'),
    path('api/bus_route/detail/<int:pk>/', apis_flota.bus_route_detail_view, name='api-bus_route-detail'),

    # VIEWs
    path('bus/list/', view_flota.bus_list, name='bus-list'),
    path('chauffeur/list/', view_flota.chauffeur_list, name='chauffeur-list'),
    path('route/list/', view_flota.route_list, name='route-list'),
    path('schedule/list/', view_flota.schedule_list, name='schedule-list'),
]

agencia/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    {% block css %}
    {% endblock css %}
    <title>{{title}}</title>
  </head>
  <body>
    <div class="container">
        {% include 'headers.html' %}
        <div class="row">
            <div class="col-lg-12">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <script type='text/javascript' src="{% static 'vue/vue.js' %}" ></script>
    <script src="{% static 'js/axios.min.js' %}" ></script>

    <!-- Bootstrap Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
    {% block js %}
    {% endblock js %}
  </body>
</html>

agencia/templates/headers.html
<header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="{% url 'home' %}" class="nav-link {% if nav_item == 'home' %}active{% endif %}">Home</a></li>
      <li class="nav-item"><a href="{% url 'garage:bus-list'%}" class="nav-link {% if nav_item == 'bus' %}active{% endif %}">Buses</a></li>
      <li class="nav-item"><a href="{% url 'garage:chauffeur-list'%}" class="nav-link {% if nav_item == 'chauffeur' %}active{% endif %}">Chauffeur</a></li>
      <li class="nav-item"><a href="{% url 'garage:route-list'%}" class="nav-link {% if nav_item == 'route' %}active{% endif %}">Routes</a></li>
      <li class="nav-item"><a href="{% url 'garage:schedule-list'%}" class="nav-link {% if nav_item == 'schedule' %}active{% endif %}">Schedules</a></li>
      <li class="nav-item"><a href="{% url 'box_office:statistics'%}" class="nav-link {% if nav_item == 'statistics' %}active{% endif %}">Statistics</a></li>
      <li class="nav-item"><a href="{% url 'box_office:ticket-buy'%}" class="nav-link {% if nav_item == 'ticket' %}active{% endif %}">Buy Sell</a></li>
    </ul>
</header>

agencia/templates/home.html
{% extends 'base.html' %}

agencia/templates/navbar.html
<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#" >Bus agency</a>
    </div>
  </nav>